---
apiVersion: v1
kind: Service
metadata:
  name: post-storage-memcached
  labels:
    death-star-project: social-network
    app: post-storage-memcached
  namespace: social-network
spec:
  ports:
  - port: 11211
  selector:
    death-star-project: social-network
    app: post-storage-memcached
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-storage-memcached
  labels:
    death-star-project: social-network
    app: post-storage-memcached
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: post-storage-memcached
  template:
    metadata:
      labels:
        death-star-project: social-network
        app: post-storage-memcached
      name: post-storage-memcached
    spec:
      runtimeClassName: kata-fc
      containers:
      - name: post-storage-memcached
        image: memcached
        env:
        - name: GUEST_IMAGE
          value: docker.io/library/memcached:latest
        - name: GUEST_PORT
          value: "11211"
        - name: K_REVISION
          value: post-storage-memcached-00001
      restartPolicy: Always
