---
apiVersion: v1
kind: Service
metadata:
  name: social-graph-mongodb
  labels:
    death-star-project: social-network
    app: social-graph-mongodb
  namespace: social-network
spec:
  ports:
  - port: 27017
  selector:
    death-star-project: social-network
    app: social-graph-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-graph-mongodb
  labels:
    death-star-project: social-network
    app: social-graph-mongodb
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: social-graph-mongodb
  template:
    metadata:
      labels:
        death-star-project: social-network
        app: social-graph-mongodb
      name: social-graph-mongodb
    spec:
      runtimeClassName: kata-fc
      containers:
      - name: social-graph-mongodb
        image: mongo:4.4.6
        env:
        - name: GUEST_IMAGE
          value: docker.io/library/mongo:4.4.6
        - name: GUEST_PORT
          value: "27017"
        - name: K_REVISION
          value: social-graph-mongodb-00001
        volumeMounts:
          - name: my-data
            mountPath: "/data/db"
      restartPolicy: Always
      volumes:
      - name: my-data
        emptyDir: {}
