---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-client
  labels:
    death-star-project: social-network
    app: ubuntu-client
  namespace: social-network
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: ubuntu-client
  template:
    metadata:
      labels:
        death-star-project: social-network
        app: ubuntu-client
      name: ubuntu-client
    spec:
      runtimeClassName: kata-fc
      containers:
      # - name: ubuntu-client
      #   image: michaelirey/ubuntu-with-tools
      #   command: ["sleep", "infinity"]
      #   imagePullPolicy: IfNotPresent
      - name: ubuntu-client
        image: deathstarbench/wrk2-client
        env:
        - name: GUEST_IMAGE
          value: docker.io/deathstarbench/wrk2-client:latest
        - name: GUEST_PORT
          value: "8080"
        - name: K_REVISION
          value: ubuntu-client-00001
        command:  ["/bin/sh"]
        args:
          - -c
          - sleep 365d
        imagePullPolicy: Always
      - name: python
        image: demisto/py3-tools:1.0.0.3728574
        env:
        - name: GUEST_IMAGE
          value: docker.io/demisto/py3-tools:1.0.0.3728574
        - name: GUEST_PORT
          value: "8080"
        - name: K_REVISION
          value: ubuntu-client-python-00001
        command: ["sleep", "infinity"]
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
